
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Daftar_buku extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_buku
     */
    public Daftar_buku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lbPerpus = new javax.swing.JLabel();
        lbUP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Arsitektur = new javax.swing.JPanel();
        lbArsitek = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelArsitek = new javax.swing.JTable();
        cbxElek3 = new javax.swing.JCheckBox();
        cbxElek4 = new javax.swing.JCheckBox();
        btnElek1 = new javax.swing.JButton();
        btnHapusElek1 = new javax.swing.JButton();
        elektro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelElektro = new javax.swing.JTable();
        lbElektro = new javax.swing.JLabel();
        cbxElek1 = new javax.swing.JCheckBox();
        cbxElek2 = new javax.swing.JCheckBox();
        btnElek = new javax.swing.JButton();
        btnHapusElek = new javax.swing.JButton();
        Industri = new javax.swing.JPanel();
        lbIndustri = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelIndustri = new javax.swing.JTable();
        cbxIds1 = new javax.swing.JCheckBox();
        cbxIds2 = new javax.swing.JCheckBox();
        btnEditIds = new javax.swing.JButton();
        btnHapusIds = new javax.swing.JButton();
        Informatika = new javax.swing.JPanel();
        lbIT = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelIT = new javax.swing.JTable();
        cbxIT1 = new javax.swing.JCheckBox();
        cbxIT2 = new javax.swing.JCheckBox();
        btnEditIT = new javax.swing.JButton();
        btnHapusIT = new javax.swing.JButton();
        Mesin = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelMesin = new javax.swing.JTable();
        lbMesin = new javax.swing.JLabel();
        btnEditMesin = new javax.swing.JButton();
        btnHapusMesin = new javax.swing.JButton();
        cbxMesin2 = new javax.swing.JCheckBox();
        cbxMesin1 = new javax.swing.JCheckBox();
        Sipil = new javax.swing.JPanel();
        lbSipil = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelSipil = new javax.swing.JTable();
        cbxSipil1 = new javax.swing.JCheckBox();
        cbxSipil2 = new javax.swing.JCheckBox();
        btnHapusSipil = new javax.swing.JButton();
        btnEditSipil = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan UP - Daftar Buku");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        lbPerpus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPerpus.setText("Perpustakaan");

        lbUP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUP.setText("Universitas Pancasila");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPerpus)
                    .addComponent(lbUP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(lbPerpus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbUP))
                    .addComponent(logo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbArsitek.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbArsitek.setText("Daftar Buku Arsitektrur");

        tabelArsitek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Mengatasi runtuhnya beton", "1"},
                {"2", "7 cara membuat rumah anti gempa", "2"}
            },
            new String [] {
                "No", "Nama Buku", "No. Rak"
            }
        ));
        tabelArsitek.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabelArsitek);

        cbxElek3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxElek3ActionPerformed(evt);
            }
        });

        cbxElek4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxElek4ActionPerformed(evt);
            }
        });

        btnElek1.setText("Edit");

        btnHapusElek1.setText("Hapus");

        javax.swing.GroupLayout ArsitekturLayout = new javax.swing.GroupLayout(Arsitektur);
        Arsitektur.setLayout(ArsitekturLayout);
        ArsitekturLayout.setHorizontalGroup(
            ArsitekturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArsitekturLayout.createSequentialGroup()
                .addGroup(ArsitekturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ArsitekturLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lbArsitek)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ArsitekturLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ArsitekturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ArsitekturLayout.createSequentialGroup()
                                .addComponent(btnElek1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapusElek1))
                            .addGroup(ArsitekturLayout.createSequentialGroup()
                                .addGroup(ArsitekturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxElek3)
                                    .addComponent(cbxElek4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ArsitekturLayout.setVerticalGroup(
            ArsitekturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArsitekturLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbArsitek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ArsitekturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArsitekturLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ArsitekturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapusElek1)
                            .addComponent(btnElek1)))
                    .addGroup(ArsitekturLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cbxElek3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxElek4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arsitektur", Arsitektur);

        tabelElektro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cara aman main listrik", "14"},
                {"2", "Fisika Tingkat Dewa", "12"}
            },
            new String [] {
                "No", "Nama Buku", "No. Rak"
            }
        ));
        tabelElektro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tabelElektro);

        lbElektro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbElektro.setText("Daftar Buku Elektro");

        cbxElek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxElek1ActionPerformed(evt);
            }
        });

        cbxElek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxElek2ActionPerformed(evt);
            }
        });

        btnElek.setText("Edit");

        btnHapusElek.setText("Hapus");

        javax.swing.GroupLayout elektroLayout = new javax.swing.GroupLayout(elektro);
        elektro.setLayout(elektroLayout);
        elektroLayout.setHorizontalGroup(
            elektroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elektroLayout.createSequentialGroup()
                .addGroup(elektroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(elektroLayout.createSequentialGroup()
                        .addComponent(btnElek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusElek))
                    .addGroup(elektroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(elektroLayout.createSequentialGroup()
                            .addGap(214, 214, 214)
                            .addComponent(lbElektro))
                        .addGroup(elektroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(elektroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxElek1)
                                .addComponent(cbxElek2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        elektroLayout.setVerticalGroup(
            elektroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elektroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbElektro)
                .addGroup(elektroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elektroLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cbxElek1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxElek2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE))
                    .addGroup(elektroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(elektroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusElek)
                    .addComponent(btnElek))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Elektro", elektro);

        lbIndustri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIndustri.setText("Daftar Buku Industri");

        tabelIndustri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Tata cara menjadi manajer yang baik", "6"},
                {"2", "Sistem Cerdas", "8"}
            },
            new String [] {
                "No", "Nama Buku", "No. Rak"
            }
        ));
        tabelIndustri.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(tabelIndustri);

        cbxIds1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIds1ActionPerformed(evt);
            }
        });

        cbxIds2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIds2ActionPerformed(evt);
            }
        });

        btnEditIds.setText("Edit");

        btnHapusIds.setText("Hapus");

        javax.swing.GroupLayout IndustriLayout = new javax.swing.GroupLayout(Industri);
        Industri.setLayout(IndustriLayout);
        IndustriLayout.setHorizontalGroup(
            IndustriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndustriLayout.createSequentialGroup()
                .addGroup(IndustriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IndustriLayout.createSequentialGroup()
                        .addComponent(btnEditIds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusIds))
                    .addGroup(IndustriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IndustriLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(IndustriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxIds1)
                                .addComponent(cbxIds2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(IndustriLayout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(lbIndustri))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        IndustriLayout.setVerticalGroup(
            IndustriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndustriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIndustri)
                .addGroup(IndustriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IndustriLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cbxIds1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxIds2))
                    .addGroup(IndustriLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(IndustriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusIds)
                    .addComponent(btnEditIds))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Industri", Industri);

        lbIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIT.setText("Daftar Buku Informatika");

        tabelIT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "JAVA Dasar", "26"},
                {"2", "PHP 5", "20"}
            },
            new String [] {
                "No", "Nama Buku", "No. Rak"
            }
        ));
        tabelIT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(tabelIT);

        cbxIT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIT1ActionPerformed(evt);
            }
        });

        cbxIT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIT2ActionPerformed(evt);
            }
        });

        btnEditIT.setText("Edit");
        btnEditIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditITActionPerformed(evt);
            }
        });

        btnHapusIT.setText("Hapus");
        btnHapusIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InformatikaLayout = new javax.swing.GroupLayout(Informatika);
        Informatika.setLayout(InformatikaLayout);
        InformatikaLayout.setHorizontalGroup(
            InformatikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformatikaLayout.createSequentialGroup()
                .addGroup(InformatikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InformatikaLayout.createSequentialGroup()
                        .addComponent(btnEditIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusIT))
                    .addGroup(InformatikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InformatikaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(InformatikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxIT1)
                                .addComponent(cbxIT2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(InformatikaLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(lbIT))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        InformatikaLayout.setVerticalGroup(
            InformatikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformatikaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIT)
                .addGroup(InformatikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformatikaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(cbxIT1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxIT2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                    .addGroup(InformatikaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(InformatikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusIT)
                    .addComponent(btnEditIT))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Informatika", Informatika);

        tabelMesin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Mencampur OLI dengan baik", "29"},
                {"2", "Onderdil yang baik", "29"}
            },
            new String [] {
                "No", "Nama Buku", "No. Rak"
            }
        ));
        tabelMesin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(tabelMesin);

        lbMesin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMesin.setText("Daftar Buku Mesin");

        btnEditMesin.setText("Edit");

        btnHapusMesin.setText("Hapus");

        cbxMesin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesin2ActionPerformed(evt);
            }
        });

        cbxMesin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MesinLayout = new javax.swing.GroupLayout(Mesin);
        Mesin.setLayout(MesinLayout);
        MesinLayout.setHorizontalGroup(
            MesinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MesinLayout.createSequentialGroup()
                .addGroup(MesinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MesinLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbMesin))
                    .addGroup(MesinLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(MesinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxMesin1)
                            .addComponent(cbxMesin2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MesinLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnEditMesin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusMesin)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        MesinLayout.setVerticalGroup(
            MesinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MesinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMesin)
                .addGroup(MesinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MesinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MesinLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(cbxMesin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMesin2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MesinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusMesin)
                    .addComponent(btnEditMesin))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mesin", Mesin);

        lbSipil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSipil.setText("Daftar Buku Sipil");

        tabelSipil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Menjaga keseimbangan Jembatan", "31"},
                {"2", "Tata cara ruang taman", "32"}
            },
            new String [] {
                "No", "Nama Buku", "No. Rak"
            }
        ));
        tabelSipil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane6.setViewportView(tabelSipil);

        cbxSipil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSipil1ActionPerformed(evt);
            }
        });

        cbxSipil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSipil2ActionPerformed(evt);
            }
        });

        btnHapusSipil.setText("Hapus");

        btnEditSipil.setText("Edit");

        javax.swing.GroupLayout SipilLayout = new javax.swing.GroupLayout(Sipil);
        Sipil.setLayout(SipilLayout);
        SipilLayout.setHorizontalGroup(
            SipilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SipilLayout.createSequentialGroup()
                .addGroup(SipilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SipilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEditSipil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusSipil))
                    .addGroup(SipilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SipilLayout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(lbSipil))
                        .addGroup(SipilLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(SipilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxSipil1)
                                .addComponent(cbxSipil2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        SipilLayout.setVerticalGroup(
            SipilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SipilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSipil)
                .addGroup(SipilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SipilLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SipilLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cbxSipil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSipil2)))
                .addGap(18, 18, 18)
                .addGroup(SipilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusSipil)
                    .addComponent(btnEditSipil))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sipil", Sipil);

        btnKembali.setText("Kembali");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSipil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSipil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSipil1ActionPerformed

    private void cbxSipil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSipil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSipil2ActionPerformed

    private void cbxMesin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesin2ActionPerformed

    private void cbxMesin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesin1ActionPerformed

    private void cbxIT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIT1ActionPerformed

    private void cbxIT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIT2ActionPerformed

    private void cbxIds1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIds1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIds1ActionPerformed

    private void cbxIds2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIds2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIds2ActionPerformed

    private void cbxElek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxElek1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxElek1ActionPerformed

    private void cbxElek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxElek2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxElek2ActionPerformed

    private void cbxElek3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxElek3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxElek3ActionPerformed

    private void cbxElek4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxElek4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxElek4ActionPerformed

    private void btnEditITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditITActionPerformed
        Edit_buku eb = new Edit_buku();
        eb.setTampil(true);
    }//GEN-LAST:event_btnEditITActionPerformed

    private void btnHapusITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusITActionPerformed
         JOptionPane.showMessageDialog(this, "Data Sudah Dihapus","Hapus", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnHapusITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_buku().setVisible(false);
            }
        });
    }
    public void setTampil(boolean tampil){
        new Daftar_buku().setVisible(tampil);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arsitektur;
    private javax.swing.JPanel Industri;
    private javax.swing.JPanel Informatika;
    private javax.swing.JPanel Mesin;
    private javax.swing.JPanel Sipil;
    private javax.swing.JButton btnEditIT;
    private javax.swing.JButton btnEditIds;
    private javax.swing.JButton btnEditMesin;
    private javax.swing.JButton btnEditSipil;
    private javax.swing.JButton btnElek;
    private javax.swing.JButton btnElek1;
    private javax.swing.JButton btnHapusElek;
    private javax.swing.JButton btnHapusElek1;
    private javax.swing.JButton btnHapusIT;
    private javax.swing.JButton btnHapusIds;
    private javax.swing.JButton btnHapusMesin;
    private javax.swing.JButton btnHapusSipil;
    private javax.swing.JButton btnKembali;
    private javax.swing.JCheckBox cbxElek1;
    private javax.swing.JCheckBox cbxElek2;
    private javax.swing.JCheckBox cbxElek3;
    private javax.swing.JCheckBox cbxElek4;
    private javax.swing.JCheckBox cbxIT1;
    private javax.swing.JCheckBox cbxIT2;
    private javax.swing.JCheckBox cbxIds1;
    private javax.swing.JCheckBox cbxIds2;
    private javax.swing.JCheckBox cbxMesin1;
    private javax.swing.JCheckBox cbxMesin2;
    private javax.swing.JCheckBox cbxSipil1;
    private javax.swing.JCheckBox cbxSipil2;
    private javax.swing.JPanel elektro;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbArsitek;
    private javax.swing.JLabel lbElektro;
    private javax.swing.JLabel lbIT;
    private javax.swing.JLabel lbIndustri;
    private javax.swing.JLabel lbMesin;
    private javax.swing.JLabel lbPerpus;
    private javax.swing.JLabel lbSipil;
    private javax.swing.JLabel lbUP;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tabelArsitek;
    private javax.swing.JTable tabelElektro;
    private javax.swing.JTable tabelIT;
    private javax.swing.JTable tabelIndustri;
    private javax.swing.JTable tabelMesin;
    private javax.swing.JTable tabelSipil;
    // End of variables declaration//GEN-END:variables
}
