/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class Index extends javax.swing.JFrame {
    //public Index index;
    public Connection con;
    public Statement stt;
    public PreparedStatement pst;
    private ResultSet rs;
    
    public Index() {
        initComponents();
        Update_table_User();
        Update_table();
        koneksi();
        /*try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            stt = con.createStatement();
            JOptionPane.showMessageDialog(null, "Berhasil Koneksi Database");
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Tidak Berhasil Koneksi ke Database");
        }*/
    }
    
    private void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            stt = con.createStatement();
            //JOptionPane.showMessageDialog(null, "Berhasil Koneksi Database");
            System.out.println("Berhasil Koneksi Database");
        }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Tidak Berhasil Koneksi ke Database");
        }
    }
    private void Update_table_User(){
        try{
            koneksi();
            //String query = "select id_buku,nama_buku,no_rak from buku where id_kategori = 4";
            String query = "select * from user";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            tabelUser.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    private void Update_table(){
        try{
            koneksi();
            //String query = "select id_buku,nama_buku,no_rak from buku where id_kategori = 4";
            String query = "select * from buku order by id_buku";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            tabelBuku.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lbPerpus = new javax.swing.JLabel();
        lbUP = new javax.swing.JLabel();
        tabulasi = new javax.swing.JTabbedPane();
        DaftarUser = new javax.swing.JPanel();
        formRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtkonfirmasi = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtjurusan = new javax.swing.JTextField();
        btndaftar = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtnpm = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        cmbKelamin = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        lbDaftarUser = new javax.swing.JLabel();
        DaftarBuku = new javax.swing.JPanel();
        lbDaftarBuku = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelBuku = new javax.swing.JTable();
        form = new javax.swing.JPanel();
        txtNamaBuku = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtPenulis = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        cmbKategori = new javax.swing.JComboBox();
        txtNoRak = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lbNoRak = new javax.swing.JLabel();
        lbKategori = new javax.swing.JLabel();
        lbDeskripsi = new javax.swing.JLabel();
        lbPenerbit = new javax.swing.JLabel();
        lbPenulis = new javax.swing.JLabel();
        lbNamaBuku = new javax.swing.JLabel();
        lbISBN = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        lbTmbahBuku = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        lbKataKunci = new javax.swing.JLabel();
        txtSeacrh = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        logoSearch = new javax.swing.JLabel();
        lbSearch = new javax.swing.JLabel();
        lbHasil = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelSearch = new javax.swing.JTable();
        AboutUs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan UP - Admin Panel");
        setResizable(false);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        lbPerpus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPerpus.setText("Perpustakaan");

        lbUP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUP.setText("Universitas Pancasila");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPerpus)
                    .addComponent(lbUP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(lbPerpus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUP))
                    .addComponent(logo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabulasi.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("User Name");

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        jLabel3.setText("Konfirmasi");

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Email");

        jLabel7.setText("Jurusan");

        jLabel8.setText("NPM");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        txtjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjurusanActionPerformed(evt);
            }
        });

        btndaftar.setText("Daftar");
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel9.setText("Alamat");

        txtnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnpmActionPerformed(evt);
            }
        });

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane4.setViewportView(txtalamat);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Register");

        cmbKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pria", "Wanita" }));

        javax.swing.GroupLayout formRegisterLayout = new javax.swing.GroupLayout(formRegister);
        formRegister.setLayout(formRegisterLayout);
        formRegisterLayout.setHorizontalGroup(
            formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btndaftar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(formRegisterLayout.createSequentialGroup()
                            .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formRegisterLayout.createSequentialGroup()
                        .addComponent(btncancel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formRegisterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnama)
                            .addComponent(txtusername)
                            .addComponent(txtpassword)
                            .addComponent(txtkonfirmasi)
                            .addComponent(txtemail)
                            .addComponent(txtnpm)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtjurusan))))
                .addContainerGap())
            .addGroup(formRegisterLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formRegisterLayout.setVerticalGroup(
            formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRegisterLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncancel)
                            .addComponent(btndaftar))
                        .addGap(21, 21, 21))
                    .addGroup(formRegisterLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))))
        );

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelUser);

        lbDaftarUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbDaftarUser.setText("Daftar User");

        javax.swing.GroupLayout DaftarUserLayout = new javax.swing.GroupLayout(DaftarUser);
        DaftarUser.setLayout(DaftarUserLayout);
        DaftarUserLayout.setHorizontalGroup(
            DaftarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarUserLayout.createSequentialGroup()
                .addGroup(DaftarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaftarUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DaftarUserLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lbDaftarUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(formRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        DaftarUserLayout.setVerticalGroup(
            DaftarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DaftarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DaftarUserLayout.createSequentialGroup()
                        .addComponent(lbDaftarUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabulasi.addTab("Daftar User", DaftarUser);

        lbDaftarBuku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbDaftarBuku.setText("Daftar Buku Fakultas Teknik");

        tabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "title 1", "title 2", "title 3"
            }
        ));
        tabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBukuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelBuku);

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtDeskripsi);

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kategori", "Arsitektur", "Elektro", "Industri", "Informatika", "Mesin", "Sipil" }));
        cmbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategoriActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbNoRak.setText("No Rak");

        lbKategori.setText("Kategori");

        lbDeskripsi.setText("Deskripsi");

        lbPenerbit.setText("Penerbit");

        lbPenulis.setText("Penulis");

        lbNamaBuku.setText("Nama Buku");

        lbISBN.setText("ISBN");

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Delete");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        lbTmbahBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTmbahBuku.setText("Tambah Buku");

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(formLayout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel))
                            .addGroup(formLayout.createSequentialGroup()
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNoRak)
                                    .addComponent(lbNamaBuku)
                                    .addComponent(lbISBN)
                                    .addComponent(lbPenulis)
                                    .addComponent(lbPenerbit)
                                    .addComponent(lbDeskripsi)
                                    .addComponent(lbKategori))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNoRak, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbKategori, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPenerbit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPenulis, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNamaBuku, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lbTmbahBuku)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lbTmbahBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbISBN))
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNamaBuku))
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPenulis))
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPenerbit))
                .addGap(29, 29, 29)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDeskripsi))
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKategori))
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNoRak))
                .addGap(26, 26, 26)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout DaftarBukuLayout = new javax.swing.GroupLayout(DaftarBuku);
        DaftarBuku.setLayout(DaftarBukuLayout);
        DaftarBukuLayout.setHorizontalGroup(
            DaftarBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarBukuLayout.createSequentialGroup()
                .addGroup(DaftarBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaftarBukuLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbDaftarBuku))
                    .addGroup(DaftarBukuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        DaftarBukuLayout.setVerticalGroup(
            DaftarBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DaftarBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaftarBukuLayout.createSequentialGroup()
                        .addComponent(lbDaftarBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabulasi.addTab("Daftar Buku", DaftarBuku);

        lbKataKunci.setText("Masukan Nama Buku");

        txtSeacrh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSeacrh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeacrhActionPerformed(evt);
            }
        });
        txtSeacrh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeacrhKeyReleased(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnsearch.png"))); // NOI18N

        logoSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        lbSearch.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbSearch.setText("Searching");

        lbHasil.setText("Hasil Pencarian");

        tabelSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "title 1", "title 2", "title 3"
            }
        ));
        jScrollPane2.setViewportView(tabelSearch);

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSearch))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lbKataKunci)
                        .addGap(50, 50, 50)
                        .addComponent(txtSeacrh, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbHasil))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbSearch))
                    .addGroup(searchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoSearch)))
                .addGap(33, 33, 33)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKataKunci)
                    .addComponent(txtSeacrh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(33, 33, 33)
                .addComponent(lbHasil)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        tabulasi.addTab("Search", search);

        javax.swing.GroupLayout AboutUsLayout = new javax.swing.GroupLayout(AboutUs);
        AboutUs.setLayout(AboutUsLayout);
        AboutUsLayout.setHorizontalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        AboutUsLayout.setVerticalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        tabulasi.addTab("About Us", AboutUs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabulasi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{
            try{                
                //cmbKategori.setSelectedIndex(4);
                
                String sql = "Insert into buku (id_buku, nama_buku, penulis, penerbit, deskripsi, no_rak, id_kategori) values(?,?,?,?,?,?,4)";
                pst = con.prepareStatement(sql);
                pst.setString(1, txtISBN.getText());
                pst.setString(2, txtNamaBuku.getText());
                pst.setString(3, txtPenulis.getText());
                pst.setString(4, txtPenerbit.getText());
                pst.setString(5, txtDeskripsi.getText());
                pst.setString(6, txtNoRak.getText());
                
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data gagal disimpan di simpan");
            }
            Update_table();
            //isbn
            try{
                int isbn = Integer.parseInt(
                    this.txtISBN.getText());
                System.out.println("ISBN : " + isbn);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "ISBN belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //nama buku
            try{
                String nmbuku = this.txtNamaBuku.getText();
                System.out.println("Nama Buku : " + nmbuku);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Nama Buku belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //penulis
            try{
                String penulis = this.txtPenulis.getText();
                System.out.println("Penulis : " + penulis);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Penulis belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //penerbit
            try{
                String penerbit = this.txtPenerbit.getText();                
                System.out.println("Penerbit : " + penerbit);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Penerbit belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //deskripsi
            try{
                String deskripsi = this.txtDeskripsi.getText();
                System.out.println("Deskripsi Buku : " + deskripsi);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Deskripsi Buku belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //kategori
            try{
                String kateg = (String) cmbKategori.getSelectedItem();
                if(kateg == "Informatika"){
                    int id = 4;
                    System.out.println("Kategori Buku : " + id);
                }else{
                    int id = 2;
                    System.out.println("Kategori Buku : " + id);
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Kategori Buku belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //no rak
            try{
                int norak = Integer.parseInt(
                    this.txtNoRak.getText());
                System.out.println("No. Rak Buku : " + norak);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "No. Rak belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            System.out.println("===================================");            
            txtISBN.setText("");
            txtISBN.requestFocus();
            txtNamaBuku.setText("");
            txtNamaBuku.requestFocus();
            txtPenulis.setText("");
            txtPenulis.requestFocus();
            txtPenerbit.setText("");
            txtPenerbit.requestFocus();
            txtDeskripsi.setText("");
            txtDeskripsi.requestFocus();
            cmbKategori.setSelectedItem("Pilih Kategori");
            cmbKategori.requestFocus();
            txtNoRak.setText("");
            txtNoRak.requestFocus();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Gagal Diinput", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtISBN.setText("");
        txtISBN.requestFocus();
        txtNamaBuku.setText("");
        txtNamaBuku.requestFocus();
        txtPenulis.setText("");
        txtPenulis.requestFocus();
        txtPenerbit.setText("");
        txtPenerbit.requestFocus();
        txtDeskripsi.setText("");
        txtDeskripsi.requestFocus();
        cmbKategori.setSelectedItem("Pilih Kategori");
        cmbKategori.requestFocus();
        txtNoRak.setText("");
        txtNoRak.requestFocus();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            String eISBN = txtISBN.getText();
            String eNmBuku = txtNamaBuku.getText();
            String ePenulis = txtPenulis.getText();
            String ePenerbit = txtPenerbit.getText();
            String eDeskripsi = txtDeskripsi.getText();
            String eNoRak = txtNoRak.getText();
            
            String sqlEdit = "update buku set id_buku = '"+eISBN+"', nama_buku = '"+eNmBuku+"', penulis = '"+ePenulis+"', penerbit = '"+ePenerbit+"', deskripsi = '"+eDeskripsi+"', no_rak = '"+eNoRak+"' where id_buku = '"+eISBN+"'";
            pst = con.prepareStatement(sqlEdit);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data berhasil di Update");
            
            txtISBN.setText("");
            txtISBN.requestFocus();
            txtNamaBuku.setText("");
            txtNamaBuku.requestFocus();
            txtPenulis.setText("");
            txtPenulis.requestFocus();
            txtPenerbit.setText("");
            txtPenerbit.requestFocus();
            txtDeskripsi.setText("");
            txtDeskripsi.requestFocus();
            cmbKategori.setSelectedItem("Pilih Kategori");
            cmbKategori.requestFocus();
            txtNoRak.setText("");
            txtNoRak.requestFocus();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategoriActionPerformed

    private void tabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBukuMouseClicked
        btnUpdate.setEnabled(true); 
        btnHapus.setEnabled(true);
        btnSave.setEnabled(false);
        int row = tabelBuku.getSelectedRow();
         txtISBN.setText(tabelBuku.getModel().getValueAt(row, 0).toString());
         txtNamaBuku.setText(tabelBuku.getModel().getValueAt(row, 1).toString());
         txtPenulis.setText(tabelBuku.getModel().getValueAt(row, 2).toString());
         txtPenerbit.setText(tabelBuku.getModel().getValueAt(row, 3).toString());
         txtDeskripsi.setText(tabelBuku.getModel().getValueAt(row, 4).toString());
         txtNoRak.setText(tabelBuku.getModel().getValueAt(row, 5).toString());
    }//GEN-LAST:event_tabelBukuMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
          String sql = "delete from buku where id_buku = ?";
          try{
              pst = con.prepareStatement(sql);
              pst.setString(1, txtISBN.getText());
              pst.execute();
              JOptionPane.showMessageDialog(null, "Delete");
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
          Update_table();
          txtISBN.setText("");
          txtISBN.requestFocus();
          txtNamaBuku.setText("");
          txtNamaBuku.requestFocus();
          txtPenulis.setText("");
          txtPenulis.requestFocus();
          txtPenerbit.setText("");
          txtPenerbit.requestFocus();
          txtDeskripsi.setText("");
          txtDeskripsi.requestFocus();
          cmbKategori.setSelectedItem("Pilih Kategori");
          cmbKategori.requestFocus();
          txtNoRak.setText("");
          txtNoRak.requestFocus();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtSeacrhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeacrhKeyReleased
         try{
             String sql = "select * from buku where nama_buku = ?";
             pst = con.prepareStatement(sql);
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_txtSeacrhKeyReleased

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed

    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjurusanActionPerformed

    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
        //user
        try{
            String Username = this.txtusername.getText();
            System.out.println("User name : " + Username);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "User Name belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //password
        try{
            int Password = Integer.parseInt(
                this.txtpassword.getText());
            System.out.println("Password : " + Password);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Password belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //konfirmasi
        try{
            int konfirmasi = Integer.parseInt(
                this.txtkonfirmasi.getText());
            System.out.println("Konfirmasi : " + konfirmasi);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Konfirmasi belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Nama Lengkap
        try{
            String nama = this.txtnama.getText();
            System.out.println("Nama Lengkap : " + nama);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Nama Lengkap belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Jenis Kelamin
        try{
            String kelamin = (String) cmbKelamin.getSelectedItem();
            System.out.println("Kategori : " + kelamin);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Jenis Kelamin Kosong","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //email
        try{
            String email = this.txtemail.getText();
            System.out.println("Email : " + email);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Email belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //jurusan
        try{
            String jurusan = this.txtjurusan.getText();
            System.out.println("Jurusan : " + jurusan);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Jurusan belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //NPM
        try{
            String npm = this.txtnpm.getText();
            System.out.println("NPM : " + npm);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "NPM belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //alamat
        try{
            String Alamat = this.txtalamat.getText();
            System.out.println("Alamat : " + Alamat);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "alamat belum diisi","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btndaftarActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnpmActionPerformed

    private void txtSeacrhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeacrhActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtSeacrhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Index().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutUs;
    private javax.swing.JPanel DaftarBuku;
    private javax.swing.JPanel DaftarUser;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndaftar;
    private javax.swing.JComboBox cmbKategori;
    private javax.swing.JComboBox cmbKelamin;
    private javax.swing.JPanel form;
    private javax.swing.JPanel formRegister;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbDaftarBuku;
    private javax.swing.JLabel lbDaftarUser;
    private javax.swing.JLabel lbDeskripsi;
    private javax.swing.JLabel lbHasil;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbKataKunci;
    private javax.swing.JLabel lbKategori;
    private javax.swing.JLabel lbNamaBuku;
    private javax.swing.JLabel lbNoRak;
    private javax.swing.JLabel lbPenerbit;
    private javax.swing.JLabel lbPenulis;
    private javax.swing.JLabel lbPerpus;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel lbTmbahBuku;
    private javax.swing.JLabel lbUP;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoSearch;
    private javax.swing.JPanel search;
    private javax.swing.JTable tabelBuku;
    private javax.swing.JTable tabelSearch;
    private javax.swing.JTable tabelUser;
    private javax.swing.JTabbedPane tabulasi;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNamaBuku;
    private javax.swing.JTextField txtNoRak;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtSeacrh;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtjurusan;
    private javax.swing.JPasswordField txtkonfirmasi;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnpm;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
